import { PrismaClient, PropertyType, PropertyStatus } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedProperties(landlordIds: string[]) {
  const properties = [
    // Houses (15)
    {
      title: "Modern 4 Bedroom House in Kigali",
      type: PropertyType.HOUSE,
      price: 800000,
      location: "Kigali, Gasabo",
      rooms: 4,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[0],
      province: "Kigali",
      district: "Gasabo",
      sector: "Remera",
      cell: "Rukiri I",
      village: "Amahoro",
      gpsLat: -1.9536,
      gpsLng: 30.0606,
      rules: ["No pets", "No smoking"],
    },
    {
      title: "Luxury Villa with Pool",
      type: PropertyType.HOUSE,
      price: 1500000,
      location: "Kigali, Kicukiro",
      rooms: 5,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[1],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Gikondo",
      cell: "Gikondo I",
      village: "Nyanza",
      gpsLat: -1.9858,
      gpsLng: 30.0619,
      rules: ["No parties", "Quiet hours after 10pm"],
    },
    {
      title: "Cozy 3 Bedroom Family Home",
      type: PropertyType.HOUSE,
      price: 600000,
      location: "Kigali, Nyarugenge",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[2],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Nyarugenge",
      cell: "Rwezamenyo",
      village: "Ubumwe",
      gpsLat: -1.9441,
      gpsLng: 30.0594,
      rules: ["Family friendly", "Garden maintenance required"],
    },
    {
      title: "Spacious 5 Bedroom House",
      type: PropertyType.HOUSE,
      price: 1200000,
      location: "Kigali, Gasabo",
      rooms: 5,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[3],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kimironko",
      cell: "Bibare",
      village: "Kibaza",
      gpsLat: -1.9403,
      gpsLng: 30.1261,
      rules: ["No smoking", "Pets allowed with deposit"],
    },
    {
      title: "Beautiful Garden House",
      type: PropertyType.HOUSE,
      price: 900000,
      location: "Kigali, Kicukiro",
      rooms: 4,
      status: PropertyStatus.RENTED,
      verified: true,
      ownerId: landlordIds[4],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Niboye",
      cell: "Gahanga",
      village: "Karembure",
      gpsLat: -1.9969,
      gpsLng: 30.1044,
      rules: ["Garden care included", "No loud music"],
    },
    {
      title: "Contemporary 3BR House",
      type: PropertyType.HOUSE,
      price: 750000,
      location: "Kigali, Gasabo",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[5],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kacyiru",
      cell: "Kamatamu",
      village: "Nyarutarama",
      gpsLat: -1.9355,
      gpsLng: 30.0944,
      rules: ["No pets", "Professional tenants preferred"],
    },
    {
      title: "Elegant Family Residence",
      type: PropertyType.HOUSE,
      price: 1100000,
      location: "Kigali, Nyarugenge",
      rooms: 4,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[6],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Kigali",
      cell: "Nyarugenge",
      village: "Muhima",
      gpsLat: -1.95,
      gpsLng: 30.0588,
      rules: ["Quiet neighborhood", "No commercial use"],
    },
    {
      title: "Charming Bungalow",
      type: PropertyType.HOUSE,
      price: 550000,
      location: "Kigali, Kicukiro",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[7],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Kanombe",
      cell: "Busanza",
      village: "Karama",
      gpsLat: -1.9647,
      gpsLng: 30.1289,
      rules: ["Small pets allowed", "No smoking indoors"],
    },
    {
      title: "Executive 4BR House",
      type: PropertyType.HOUSE,
      price: 1300000,
      location: "Kigali, Gasabo",
      rooms: 4,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[8],
      province: "Kigali",
      district: "Gasabo",
      sector: "Remera",
      cell: "Rukiri II",
      village: "Kisimenti",
      gpsLat: -1.958,
      gpsLng: 30.105,
      rules: ["Executive tenants only", "No pets"],
    },
    {
      title: "Suburban Family Home",
      type: PropertyType.HOUSE,
      price: 700000,
      location: "Kigali, Nyarugenge",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: false,
      ownerId: landlordIds[9],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Gitega",
      cell: "Gitega",
      village: "Nyamirambo",
      gpsLat: -1.9706,
      gpsLng: 30.0469,
      rules: ["Family oriented", "Quiet hours enforced"],
    },
    {
      title: "Renovated Classic House",
      type: PropertyType.HOUSE,
      price: 850000,
      location: "Kigali, Gasabo",
      rooms: 4,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[0],
      province: "Kigali",
      district: "Gasabo",
      sector: "Jabana",
      cell: "Jabana",
      village: "Karuruma",
      gpsLat: -1.91,
      gpsLng: 30.08,
      rules: ["Recently renovated", "No modifications allowed"],
    },
    {
      title: "Hillside View House",
      type: PropertyType.HOUSE,
      price: 950000,
      location: "Kigali, Kicukiro",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[1],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Gatenga",
      cell: "Gatenga",
      village: "Kagarama",
      gpsLat: -1.98,
      gpsLng: 30.075,
      rules: ["Scenic views", "No loud parties"],
    },
    {
      title: "Secure Gated House",
      type: PropertyType.HOUSE,
      price: 1000000,
      location: "Kigali, Gasabo",
      rooms: 4,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[2],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kinyinya",
      cell: "Kinyinya",
      village: "Kagugu",
      gpsLat: -1.925,
      gpsLng: 30.11,
      rules: ["24/7 security", "Gated community"],
    },
    {
      title: "Affordable Starter Home",
      type: PropertyType.HOUSE,
      price: 450000,
      location: "Kigali, Nyarugenge",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[3],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Mageragere",
      cell: "Mageragere",
      village: "Nyanza",
      gpsLat: -1.99,
      gpsLng: 30.05,
      rules: ["First time renters welcome", "No pets"],
    },
    {
      title: "Premium 5BR Estate",
      type: PropertyType.HOUSE,
      price: 1800000,
      location: "Kigali, Gasabo",
      rooms: 5,
      status: PropertyStatus.AVAILABLE,
      verified: false,
      ownerId: landlordIds[4],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kimihurura",
      cell: "Kimihurura",
      village: "Kibagabaga",
      gpsLat: -1.945,
      gpsLng: 30.1,
      rules: ["Luxury property", "High-end tenants only"],
    },

    // Apartments (15)
    {
      title: "Modern 2BR Apartment",
      type: PropertyType.APARTMENT,
      price: 400000,
      location: "Kigali, Gasabo",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[5],
      province: "Kigali",
      district: "Gasabo",
      sector: "Remera",
      cell: "Rukiri I",
      village: "Amahoro",
      gpsLat: -1.954,
      gpsLng: 30.061,
      rules: ["Elevator access", "No smoking"],
    },
    {
      title: "Penthouse Suite",
      type: PropertyType.APARTMENT,
      price: 800000,
      location: "Kigali, Kicukiro",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[6],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Gikondo",
      cell: "Gikondo II",
      village: "Nyanza",
      gpsLat: -1.986,
      gpsLng: 30.0625,
      rules: ["Top floor", "Gym access included"],
    },
    {
      title: "Studio Apartment Downtown",
      type: PropertyType.APARTMENT,
      price: 250000,
      location: "Kigali, Nyarugenge",
      rooms: 1,
      status: PropertyStatus.RENTED,
      verified: true,
      ownerId: landlordIds[7],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Nyarugenge",
      cell: "Rwezamenyo",
      village: "Ubumwe",
      gpsLat: -1.9445,
      gpsLng: 30.0598,
      rules: ["City center", "Single occupancy"],
    },
    {
      title: "Luxury 3BR Apartment",
      type: PropertyType.APARTMENT,
      price: 650000,
      location: "Kigali, Gasabo",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[8],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kimironko",
      cell: "Bibare",
      village: "Kibaza",
      gpsLat: -1.9408,
      gpsLng: 30.1265,
      rules: ["Swimming pool", "Parking included"],
    },
    {
      title: "Cozy 1BR Flat",
      type: PropertyType.APARTMENT,
      price: 300000,
      location: "Kigali, Kicukiro",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[9],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Niboye",
      cell: "Gahanga",
      village: "Karembure",
      gpsLat: -1.9975,
      gpsLng: 30.105,
      rules: ["Furnished", "Utilities included"],
    },
    {
      title: "Spacious 2BR Unit",
      type: PropertyType.APARTMENT,
      price: 450000,
      location: "Kigali, Gasabo",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[0],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kacyiru",
      cell: "Kamatamu",
      village: "Nyarutarama",
      gpsLat: -1.936,
      gpsLng: 30.095,
      rules: ["Balcony", "Pet friendly"],
    },
    {
      title: "Executive Apartment",
      type: PropertyType.APARTMENT,
      price: 700000,
      location: "Kigali, Nyarugenge",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[1],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Kigali",
      cell: "Nyarugenge",
      village: "Muhima",
      gpsLat: -1.9505,
      gpsLng: 30.0592,
      rules: ["Business district", "High-speed internet"],
    },
    {
      title: "Garden View Apartment",
      type: PropertyType.APARTMENT,
      price: 380000,
      location: "Kigali, Kicukiro",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[2],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Kanombe",
      cell: "Busanza",
      village: "Karama",
      gpsLat: -1.965,
      gpsLng: 30.1295,
      rules: ["Ground floor", "Garden access"],
    },
    {
      title: "Minimalist Studio",
      type: PropertyType.APARTMENT,
      price: 280000,
      location: "Kigali, Gasabo",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: false,
      ownerId: landlordIds[3],
      province: "Kigali",
      district: "Gasabo",
      sector: "Remera",
      cell: "Rukiri II",
      village: "Kisimenti",
      gpsLat: -1.9585,
      gpsLng: 30.1055,
      rules: ["Modern design", "No pets"],
    },
    {
      title: "Family 3BR Apartment",
      type: PropertyType.APARTMENT,
      price: 550000,
      location: "Kigali, Nyarugenge",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[4],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Gitega",
      cell: "Gitega",
      village: "Nyamirambo",
      gpsLat: -1.971,
      gpsLng: 30.0475,
      rules: ["Family friendly", "Playground nearby"],
    },
    {
      title: "Serviced Apartment",
      type: PropertyType.APARTMENT,
      price: 600000,
      location: "Kigali, Gasabo",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[5],
      province: "Kigali",
      district: "Gasabo",
      sector: "Jabana",
      cell: "Jabana",
      village: "Karuruma",
      gpsLat: -1.9105,
      gpsLng: 30.0805,
      rules: ["Cleaning service", "Concierge"],
    },
    {
      title: "Affordable 1BR",
      type: PropertyType.APARTMENT,
      price: 320000,
      location: "Kigali, Kicukiro",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[6],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Gatenga",
      cell: "Gatenga",
      village: "Kagarama",
      gpsLat: -1.9805,
      gpsLng: 30.0755,
      rules: ["Budget friendly", "Public transport nearby"],
    },
    {
      title: "Duplex Apartment",
      type: PropertyType.APARTMENT,
      price: 750000,
      location: "Kigali, Gasabo",
      rooms: 3,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[7],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kinyinya",
      cell: "Kinyinya",
      village: "Kagugu",
      gpsLat: -1.9255,
      gpsLng: 30.1105,
      rules: ["Two floors", "Private entrance"],
    },
    {
      title: "Compact Studio",
      type: PropertyType.APARTMENT,
      price: 220000,
      location: "Kigali, Nyarugenge",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[8],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Mageragere",
      cell: "Mageragere",
      village: "Nyanza",
      gpsLat: -1.9905,
      gpsLng: 30.0505,
      rules: ["Student friendly", "Affordable"],
    },
    {
      title: "Premium 2BR Condo",
      type: PropertyType.APARTMENT,
      price: 680000,
      location: "Kigali, Gasabo",
      rooms: 2,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[9],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kimihurura",
      cell: "Kimihurura",
      village: "Kibagabaga",
      gpsLat: -1.9455,
      gpsLng: 30.1005,
      rules: ["Luxury finishes", "Security 24/7"],
    },

    // Plots (5)
    {
      title: "Prime Commercial Plot",
      type: PropertyType.PLOT,
      price: 5000000,
      location: "Kigali, Gasabo",
      rooms: null,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[0],
      province: "Kigali",
      district: "Gasabo",
      sector: "Remera",
      cell: "Rukiri I",
      village: "Amahoro",
      gpsLat: -1.9545,
      gpsLng: 30.0615,
      rules: ["Commercial use", "Building permit required"],
    },
    {
      title: "Residential Land 500sqm",
      type: PropertyType.PLOT,
      price: 3000000,
      location: "Kigali, Kicukiro",
      rooms: null,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[1],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Gikondo",
      cell: "Gikondo I",
      village: "Nyanza",
      gpsLat: -1.9865,
      gpsLng: 30.063,
      rules: ["Residential only", "Utilities available"],
    },
    {
      title: "Investment Plot 1000sqm",
      type: PropertyType.PLOT,
      price: 8000000,
      location: "Kigali, Nyarugenge",
      rooms: null,
      status: PropertyStatus.SOLD,
      verified: true,
      ownerId: landlordIds[2],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Nyarugenge",
      cell: "Rwezamenyo",
      village: "Ubumwe",
      gpsLat: -1.945,
      gpsLng: 30.0602,
      rules: ["Mixed use", "Prime location"],
    },
    {
      title: "Agricultural Land 2000sqm",
      type: PropertyType.PLOT,
      price: 2000000,
      location: "Kigali, Gasabo",
      rooms: null,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[3],
      province: "Kigali",
      district: "Gasabo",
      sector: "Jabana",
      cell: "Jabana",
      village: "Karuruma",
      gpsLat: -1.911,
      gpsLng: 30.081,
      rules: ["Farming allowed", "Water access"],
    },
    {
      title: "Development Plot 750sqm",
      type: PropertyType.PLOT,
      price: 4500000,
      location: "Kigali, Kicukiro",
      rooms: null,
      status: PropertyStatus.AVAILABLE,
      verified: false,
      ownerId: landlordIds[4],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Niboye",
      cell: "Gahanga",
      village: "Karembure",
      gpsLat: -1.998,
      gpsLng: 30.1055,
      rules: ["Development ready", "Road access"],
    },

    // Rooms (5)
    {
      title: "Single Room Near University",
      type: PropertyType.ROOM,
      price: 80000,
      location: "Kigali, Gasabo",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[5],
      province: "Kigali",
      district: "Gasabo",
      sector: "Remera",
      cell: "Rukiri II",
      village: "Kisimenti",
      gpsLat: -1.959,
      gpsLng: 30.106,
      rules: ["Students only", "Shared bathroom"],
    },
    {
      title: "Furnished Room with WiFi",
      type: PropertyType.ROOM,
      price: 120000,
      location: "Kigali, Nyarugenge",
      rooms: 1,
      status: PropertyStatus.RENTED,
      verified: true,
      ownerId: landlordIds[6],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Kigali",
      cell: "Nyarugenge",
      village: "Muhima",
      gpsLat: -1.951,
      gpsLng: 30.0596,
      rules: ["WiFi included", "Shared kitchen"],
    },
    {
      title: "Budget Room Downtown",
      type: PropertyType.ROOM,
      price: 60000,
      location: "Kigali, Nyarugenge",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[7],
      province: "Kigali",
      district: "Nyarugenge",
      sector: "Gitega",
      cell: "Gitega",
      village: "Nyamirambo",
      gpsLat: -1.9715,
      gpsLng: 30.048,
      rules: ["Budget friendly", "Shared facilities"],
    },
    {
      title: "Private Room with Ensuite",
      type: PropertyType.ROOM,
      price: 150000,
      location: "Kigali, Gasabo",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[8],
      province: "Kigali",
      district: "Gasabo",
      sector: "Kacyiru",
      cell: "Kamatamu",
      village: "Nyarutarama",
      gpsLat: -1.9365,
      gpsLng: 30.0955,
      rules: ["Private bathroom", "Quiet environment"],
    },
    {
      title: "Shared Room for Students",
      type: PropertyType.ROOM,
      price: 40000,
      location: "Kigali, Kicukiro",
      rooms: 1,
      status: PropertyStatus.AVAILABLE,
      verified: true,
      ownerId: landlordIds[9],
      province: "Kigali",
      district: "Kicukiro",
      sector: "Gatenga",
      cell: "Gatenga",
      village: "Kagarama",
      gpsLat: -1.981,
      gpsLng: 30.076,
      rules: ["Shared room", "Students only"],
    },
  ];

  const createdProperties = await prisma.property.createMany({
    data: properties,
  });
  console.log(`✅ Seeded ${createdProperties.count} properties`);

  return await prisma.property.findMany();
}
